steps:
  # Install App
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    dir: "frontend"
  # Test App
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']
    dir: "frontend"
  # Build App
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: "frontend"

  # Install Functions
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    dir: 'frontend/functions'
  # Test Functions
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']
    dir: 'frontend/functions'

  # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      [
        'deploy',
        '--debug',
        '--token',
        '1//06a0ASgdGRWuTCgYIARAAGAYSNwF-L9IrLih-cz2cb_XcnEgZHIn8PTiGT0v8cJMpWB2ugZ9EvTb9mtPjkbLOa3xAjRZknqiLlug',
      ]
  dir: "frontend"
timeout: '900s'
